- name: helm install
  hosts: localhost
  become_method: sudo
  vars:
    playbookfolder: '/Linux'
  tasks:
    - include_tasks: '{{ playbookfolder }}/run-scripts.yaml'
      vars:
        bash_script: 'nfs/helm.sh'
