#  Copyright (C) 2021 Intel Corporation
#  SPDX-License-Identifier: BSD-3-Clause
apiVersion: v1
kind: Service
metadata:
  name: asr
  labels:
    app: asr
spec:
  #type: NodePort
  ports:
    - name: asr-port
      port: 50051
      targetPort: 50051
      #nodePort: 30008
      protocol: TCP
  selector:
    app: asr
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: asr-server
  labels:
    app: asr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asr
  template:
    metadata:
      labels:
        app: asr
    spec:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: mic
#                operator: In
#                values:
#                - "yes"
      containers:
        - name: asr
          image: 'amr-registry-pre.caas.intel.com/qsr/asr:1.0'
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 50051
            name: asr-port
            protocol: TCP
          envFrom:
          - configMapRef:
              name: intel-proxy
          - configMapRef:
              name: qsr-config
          readinessProbe:
            exec:
              command: ["/home/asr/grpc_health_probe", "-addr=localhost:50051"]
            initialDelaySeconds: 10
          livenessProbe:
            exec:
              command: ["/home/asr/grpc_health_probe", "-addr=localhost:50051"]
            initialDelaySeconds: 15
